Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2018-07, with the labels that each got.

#852 minimal error handling for mvp
  src/components/EnsureDevice.js
  src/components/ManagerPage/FirmwareUpdate.js
  src/components/modals/UpdateFirmware/Disclaimer.js
  src/components/modals/UpdateFirmware/Installing.js
  src/components/modals/UpdateFirmware/index.js
  src/components/modals/UpdateFirmware/steps/01-step-install-full-firmware.js
  src/components/modals/UpdateFirmware/steps/02-step-flash-mcu.js
  src/components/modals/UpdateFirmware/steps/03-step-confirmation.js
  src/helpers/firmware/installFinalFirmware.js
  src/helpers/firmware/installMcu.js
  src/helpers/firmware/installOsuFirmware.js
  static/i18n/en/app.yml
  static/i18n/en/errors.yml
Labels: HODL

#880 missing some errors
  static/i18n/en/errors.yml
Labels: HODL

#896 clean constants for web socket urls
  src/config/constants.js
  src/helpers/apps/installApp.js
  src/helpers/apps/uninstallApp.js
  src/helpers/urls.js
Labels: HODL

#1147 Refacto wording
  package.json
  scripts/detect-unused-wordings.js
  src/components/SettingsPage/sections/CurrencyRows.js
  src/renderer/i18n/electron.js
  src/renderer/i18n/storybook.js
  static/i18n/en/app.json
  static/i18n/en/app.yml
  static/i18n/en/errors.json
  static/i18n/en/errors.yml
  static/i18n/en/language.json
  static/i18n/en/language.yml
  static/i18n/en/onboarding.json
  static/i18n/en/onboarding.yml
  static/i18n/fr/app.json
  static/i18n/fr/app.yml
  static/i18n/fr/errors.json
  static/i18n/fr/errors.yml
  static/i18n/fr/language.json
  static/i18n/fr/language.yml
  static/i18n/fr/onboarding.json
  static/i18n/fr/onboarding.yml
Labels: HODL

#1299 fixes #1112
  src/components/IsUnlocked.js
  src/components/Onboarding/helperComponents.js
  src/components/Onboarding/steps/Finish.js
  src/components/Onboarding/steps/Init.js
  src/components/Onboarding/steps/NoDevice.js
  src/components/Onboarding/steps/Start.js
  src/components/SettingsPage/PasswordForm.js
  src/components/SettingsPage/PasswordModal.js
  src/components/base/LedgerLiveLogo.js
  src/icons/ArrowRight.js
Labels: enhancement

#1297 Rework persistence data layer
  .circleci/config.yml
  .eslintrc
  package.json
  src/actions/accounts.js
  src/analytics/segment.js
  src/components/IsUnlocked.js
  src/components/Onboarding/steps/SetPassword.js
  src/components/SettingsPage/DisablePasswordModal.js
  src/components/SettingsPage/PasswordButton.js
  src/components/SettingsPage/PasswordForm.js
  src/components/SettingsPage/PasswordModal.js
  src/components/SettingsPage/sections/Display.js
  src/components/SettingsPage/sections/Tools.js
  src/components/TopBar/index.js
  src/components/base/InputPassword/index.js
  src/config/errors.js
  src/helpers/db/db-storybook.js
  src/helpers/db/db.js
  src/helpers/db/db.spec.js
  src/helpers/db/index.js
  src/helpers/promise.js
  src/helpers/user.js
  src/logger/index.js
  src/main/app.js
  src/main/bridge.js
  src/middlewares/db.js
  src/migrations/index.js
  src/migrations/migrations.js
  src/migrations/migrations.spec.js
  src/migrations/mocks/userdata_v1.0.5_mock-01.zip
  src/migrations/mocks/userdata_v1.0.5_mock-02-encrypted-accounts.zip
  src/reducers/application.js
  src/reducers/settings.js
  src/renderer/events.js
  src/renderer/init.js
  src/sentry/browser.js
  yarn.lock
Labels: enhancement

#1336 More modular portfolio split into components
  src/components/DashboardPage/AccountCard.js
  src/components/DashboardPage/AccountCard/Header.js
  src/components/DashboardPage/AccountCard/index.js
  src/components/DashboardPage/AccountCardList.js
  src/components/DashboardPage/AccountCardListHeader.js
  src/components/DashboardPage/AccountCardPlaceholder.js
  src/components/DashboardPage/CurrentGreetings.js
  src/components/DashboardPage/SummaryDesc.js
  src/components/DashboardPage/index.js
Labels: performance
