Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-06, with the labels that each got.

#2941 Update live-common/ledgerjs + minor bump
  package.json
  yarn.lock
Labels: important

#2933 Exchange: buy crypto
  src/main/window-lifecycle.js
  src/renderer/Default.js
  src/renderer/components/ContextMenu/AccountContextMenu.js
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/ReadOnlyAddressField.js
  src/renderer/components/SelectCurrency.js
  src/renderer/icons/Exchange.js
  src/renderer/icons/ExchangeDollar.js
  src/renderer/icons/Reset.js
  src/renderer/modals/ExchangeDeviceConfirm/index.js
  src/renderer/modals/index.js
  src/renderer/screens/account/AccountActionsDefault.js
  src/renderer/screens/account/AccountHeaderActions.js
  src/renderer/screens/account/EmptyStateAccount.js
  src/renderer/screens/dashboard/index.js
  src/renderer/screens/exchange/Buy/SelectAccountAndCurrency.js
  src/renderer/screens/exchange/Buy/index.js
  src/renderer/screens/exchange/CoinifyWidget.js
  src/renderer/screens/exchange/ExchangeBanner.js
  src/renderer/screens/exchange/History.js
  src/renderer/screens/exchange/config.js
  src/renderer/screens/exchange/hooks.js
  src/renderer/screens/exchange/index.js
  src/renderer/screens/partners/index.js
  static/i18n/en/app.json
  tests/po/page.js
  tests/specs/bullrun.spec.js
Labels: important

#2917 New Crowdin translations
  static/i18n/de/app.json
  static/i18n/el/app.json
  static/i18n/es/app.json
  static/i18n/fi/app.json
  static/i18n/fr/app.json
  static/i18n/hu/app.json
  static/i18n/it/app.json
  static/i18n/ja/app.json
  static/i18n/ko/app.json
  static/i18n/nl/app.json
  static/i18n/no/app.json
  static/i18n/pl/app.json
  static/i18n/pt/app.json
  static/i18n/ru/app.json
  static/i18n/sr/app.json
  static/i18n/sv/app.json
  static/i18n/tr/app.json
  static/i18n/zh/app.json
Labels: HODL, important

#2998 add back missing USER_ID used for firmware update incremental system
  src/renderer/live-common-setup.js
Labels: important

#3007 (csms): fix ui modals error stepper handling
  src/renderer/families/cosmos/ClaimRewardsFlowModal/Body.js
  src/renderer/families/cosmos/DelegationFlowModal/Body.js
  src/renderer/families/cosmos/RedelegationFlowModal/Body.js
  src/renderer/families/cosmos/UndelegationFlowModal/Body.js
Labels: important

#3006 bump live-common v12.33.3 + libcore 6.5.4
  package.json
  src/renderer/families/cosmos/AccountHeaderActions.js
  src/renderer/families/cosmos/Delegation/index.js
  src/renderer/modals/OperationDetails/index.js
  src/renderer/screens/account/TokensList.js
  static/i18n/en/app.json
  yarn.lock
Labels: important

#3022 Wording
  static/i18n/en/app.json
Labels: HODL

#3017 outdated app warning
  package.json
  src/renderer/components/DeviceAction/index.js
  src/renderer/components/DeviceAction/rendering.js
  static/i18n/en/app.json
  yarn.lock
Labels: important

#2856 Add ANALYTICS_CONSOLE env to show an ui that displays analytics
  src/renderer/Default.js
  src/renderer/analytics/segment.js
  src/renderer/components/AnalyticsConsole.js
Labels: important

#3031 LL-2601 Add a warning when we have txs pending confirmation
  src/renderer/components/BalanceInfos/index.js
  src/renderer/components/TransactionsPendingConfirmationWarning.js
  src/renderer/screens/account/AccountBalanceSummaryHeader.js
  static/i18n/en/app.json
  yarn.lock
Labels: important

#2988 Firmware Update refinements
  src/config/nontranslatables.js
  src/renderer/actions/settings.js
  src/renderer/components/AutoRepair.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/components/Dot.js
  src/renderer/components/FlashMCU.js
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/Updater/UpdateDot.js
  src/renderer/modals/DisclaimerModal/index.js
  src/renderer/modals/RepairModal/index.js
  src/renderer/modals/UpdateFirmwareModal/index.js
  src/renderer/modals/UpdateFirmwareModal/steps/00-step-reset-device.js
  src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.js
  src/renderer/modals/UpdateFirmwareModal/steps/03-step-confirmation.js
  src/renderer/reducers/settings.js
  src/renderer/screens/manager/AppsList/index.js
  src/renderer/screens/manager/Dashboard.js
  src/renderer/screens/manager/DeviceStorage/index.js
  src/renderer/screens/manager/FirmwareUpdate/index.js
  src/renderer/screens/manager/index.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/firmware-update-0-manager-page-snap.png
  tests/specs/__image_snapshots__/firmware-update-6-flash-mcu-done-snap.png
  tests/specs/__image_snapshots__/firmware-update-7-close-modal-snap.png
  yarn.lock
Labels: important

#3033 Add Send Bitcoin advanced options
  package.json
  src/renderer/components/FormattedVal.js
  src/renderer/components/TransactionsPendingConfirmationWarning.js
  src/renderer/families/bitcoin/CoinControlModal.js
  src/renderer/families/bitcoin/FeesField.js
  src/renderer/families/bitcoin/PickUnconfirmedRBF.js
  src/renderer/families/bitcoin/PickingStrategy.js
  src/renderer/families/bitcoin/RBF.js
  src/renderer/families/bitcoin/SendAmountFields.js
  src/renderer/screens/manager/DeviceStorage/index.js
  static/i18n/en/app.json
  yarn.lock
Labels: important
