Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-10, with the labels that each got.

#3182 LL-3387 (Storage): increase operation retention storage from 100 -> 500
  src/helpers/accountModel.js
Labels: QA

#3183 LL-3159 (RecipientAddressInput): spellcheck set to false
  src/renderer/components/RecipientAddress.js
Labels: QA

#3209 Move manager sidebar item to last position
  src/renderer/components/MainSideBar/index.js
Labels: QA

#3210 Bump live-common, add wording for newly split swap rate error
  package.json
  static/i18n/en/app.json
  yarn.lock
Labels: QA

#3229 LL-2940 Fix for experimental device action being active by default
  package.json
  src/renderer/components/DeviceAction/index.js
  src/renderer/experimental.js
  yarn.lock
Labels: QA, important

#3225 LL-3547 Allow the first launch of the app to be tracked after onboarding
  src/renderer/Default.js
  src/renderer/components/TrackAppStart.js
Labels: QA

#3223 LL-3549 Analytics onboarding + add learn crypto entry
  src/config/urls.js
  src/renderer/screens/onboarding/steps/NoDevice.js
  static/i18n/en/app.json
Labels: QA

#3226 LL-3196 (SelectCurrency): tokens blockchain indicator added on dropdown selector
  src/renderer/components/SelectCurrency.js
Labels: QA

#3230 LL-3574 Change wording for update available banner
  src/renderer/components/Updater/DebugUpdater.js
  src/renderer/components/Updater/UpdaterContext.js
  static/i18n/de/app.json
  static/i18n/en/app.json
Labels: QA

#3221 LL-3207 Improved coin control modal
  src/renderer/families/bitcoin/CoinControlModal.js
  src/renderer/families/bitcoin/CoinControlRow.js
  src/renderer/families/bitcoin/SendAmountFields.js
  static/i18n/en/app.json
Labels: QA

#3227 LL-3550 Add currency name to add account flow tracked events
  src/renderer/modals/AddAccounts/steps/StepChooseCurrency.js
  src/renderer/modals/AddAccounts/steps/StepConnectDevice.js
  src/renderer/modals/AddAccounts/steps/StepFinish.js
  src/renderer/modals/AddAccounts/steps/StepImport.js
Labels: QA

#3231 LL-3029 Add extra events to the firmware update flow
  src/renderer/modals/DisclaimerModal/index.js
  src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.js
  src/renderer/modals/UpdateFirmwareModal/steps/03-step-confirmation.js
Labels: QA

#3218 LL-2907 (AddAccounts): token conditional cta added)
  package.json
  src/renderer/modals/AddAccounts/steps/StepChooseCurrency.js
  static/i18n/en/app.json
  yarn.lock
Labels: QA

#3184 ETHjs rework
  package.json
  src/internal/index.js
  src/renderer/bridge/cache.js
  src/renderer/bridge/proxy-commands.js
  src/renderer/bridge/proxy.js
  src/renderer/experimental.js
  yarn.lock
Labels: QA, important

#3238 Simple proposal for LL-3651
  src/config/urls.js
  src/renderer/components/CurrencyDownStatusAlert.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepAccount.js
  src/renderer/modals/AddAccounts/steps/StepChooseCurrency.js
  src/renderer/modals/Receive/steps/StepAccount.js
  src/renderer/modals/Receive/steps/StepConnectDevice.js
  src/renderer/modals/Send/steps/StepAmount.js
  src/renderer/modals/Send/steps/StepRecipient.js
  src/renderer/screens/dashboard/index.js
  src/renderer/screens/exchange/Buy/SelectAccountAndCurrency.js
  src/renderer/screens/swap/Form/From.js
  src/renderer/screens/swap/Form/To.js
  static/i18n/en/app.json
Labels: QA, important

#3239 Migrate swapHistory
  package.json
  src/renderer/actions/accounts.js
  src/renderer/init.js
  yarn.lock
Labels: important

#3248 Integrate latest ethjs evolution
  package.json
  src/renderer/components/FeeSliderField.js
  src/renderer/experimental.js
  src/renderer/families/ethereum/GasPriceField.js
  yarn.lock
Labels: important

#3261 fix input background
  src/renderer/screens/account/AccountHeader.js
Labels: QA

#3257 LL-3391 websocket bridge
  src/internal/commands/index.js
  src/internal/commands/websocketBridge.js
  src/renderer/components/InfoDisplay.js
  src/renderer/components/Text.js
  src/renderer/hooks/useDeeplinking.js
  src/renderer/modals/WebSocketBridge/Bridge.js
  src/renderer/modals/WebSocketBridge/index.js
  src/renderer/modals/index.js
  src/renderer/screens/settings/sections/Experimental/index.js
  static/i18n/en/app.json
Labels: QA

#3264 Let it snow
  src/renderer/components/Modal/index.js
  src/renderer/extra/Snow.js
Labels: QA

#3263 live-common 15.7.0
  package.json
  src/main/internal-lifecycle.js
  src/main/window-lifecycle.js
  src/renderer/experimental.js
  yarn.lock
Labels: QA, important
