Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-08, with the labels that each got.

#3096 LL-2962 (OperationDetails): Tx id now shows up on two lines if required
  src/renderer/modals/OperationDetails/index.js
  src/renderer/modals/OperationDetails/styledComponents.js
Labels: QA

#3105 LL-3021 GasLeak bug fix
  src/renderer/components/Modal/index.js
Labels: QA

#3095 LL-2923 (ResetPassword): wording change
  static/i18n/en/app.json
Labels: QA

#3087 LL-2885 Update link/wording for lostSeed link
  src/config/urls.js
  src/renderer/components/Markdown.js
  src/renderer/modals/DisclaimerModal/index.js
  static/i18n/en/app.json
Labels: QA

#3093 added a new account selector component
  src/renderer/components/FormattedVal.js
  src/renderer/components/PerCurrencySelectAccount.js
  src/renderer/components/PerCurrencySelectAccount/Option.js
  src/renderer/components/PerCurrencySelectAccount/index.js
  src/renderer/components/PerCurrencySelectAccount/state.js
  src/renderer/components/Select/createStyles.js
  src/renderer/components/Select/index.js
  src/renderer/screens/exchange/Buy/SelectAccountAndCurrency.js
  src/renderer/screens/exchange/hooks.js
Labels: QA, important

#3116 Fixes flow
  src/renderer/modals/UpdateFirmwareModal/index.js
  src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.js
  src/renderer/screens/exchange/Buy/SelectAccountAndCurrency.js
Labels: important

#3120 Switch BCH address formatting to cashaddr
  package.json
  src/internal/commands/getAddress.js
  src/internal/commands/index.js
  src/renderer/bridge/proxy-commands.js
  src/renderer/bridge/proxy.js
  src/renderer/components/PerCurrencySelectAccount/state.js
  src/renderer/modals/ExchangeDeviceConfirm/index.js
  src/renderer/modals/Receive/steps/StepReceiveFunds.js
  yarn.lock
Labels: HODL, QA, important

#3119 LL-2676 Auto select currency on account buy cta click
  src/renderer/components/BuyButton.js
  src/renderer/components/PerCurrencySelectAccount/state.js
  src/renderer/modals/Send/steps/StepAmount.js
  src/renderer/screens/account/AccountHeaderActions.js
  src/renderer/screens/exchange/Buy/SelectAccountAndCurrency.js
  src/renderer/screens/exchange/Buy/index.js
Labels: QA
