Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-09, with the labels that each got.

#3144 bump libcore bindings 6.8.8
  package.json
  yarn.lock
Labels: important

#3159 bump libcore v6.8.10
  package.json
  yarn.lock
Labels: important

#3149 New Crowdin updates
  static/i18n/de/app.json
  static/i18n/el/app.json
  static/i18n/es/app.json
  static/i18n/fi/app.json
  static/i18n/fr/app.json
  static/i18n/hu/app.json
  static/i18n/it/app.json
  static/i18n/ja/app.json
  static/i18n/ko/app.json
  static/i18n/nl/app.json
  static/i18n/no/app.json
  static/i18n/pl/app.json
  static/i18n/pt/app.json
  static/i18n/ru/app.json
  static/i18n/sr/app.json
  static/i18n/sv/app.json
  static/i18n/tr/app.json
  static/i18n/zh/app.json
Labels: important

#3161 Update live-common 14.2.0
  package.json
  yarn.lock
Labels: important

#3170 LL-2938 (SendSummary): add memo field
  src/renderer/modals/Send/steps/StepSummary.js
Labels: QA

#3168 LL-3101 (ClaimRewards): modal scroll issue fix
  src/renderer/families/algorand/Rewards/ClaimRewardsFlowModal/Body.js
  src/renderer/modals/ClaimRewards/Body.js
Labels: QA

#3156 on lock screen, using the keyboard will automatically focus the passw…
  src/renderer/components/IsUnlocked.js
Labels: QA

#3169 LL-3172 (AccountPage): add an exchange CTA
  src/renderer/screens/account/AccountActionsDefault.js
  src/renderer/screens/account/AccountHeaderActions.js
  static/i18n/en/app.json
Labels: QA

#3177 update libs
  package.json
  src/renderer/components/ContextMenu/ContextMenuWrapper.js
  src/renderer/components/Updater/UpdaterContext.js
  yarn.lock
Labels: important

#3179 Fix UI for Option on the per currency account selector
  src/renderer/components/PerCurrencySelectAccount/Option.js
Labels: QA

#3175 New Crowdin updates
  static/i18n/de/app.json
  static/i18n/el/app.json
  static/i18n/es/app.json
  static/i18n/fi/app.json
  static/i18n/fr/app.json
  static/i18n/hu/app.json
  static/i18n/it/app.json
  static/i18n/ja/app.json
  static/i18n/ko/app.json
  static/i18n/nl/app.json
  static/i18n/no/app.json
  static/i18n/pl/app.json
  static/i18n/pt/app.json
  static/i18n/ru/app.json
  static/i18n/sr/app.json
  static/i18n/sv/app.json
  static/i18n/tr/app.json
  static/i18n/zh/app.json
Labels: HODL, important

#3192 @ledgerhq/cryptoassets
  package.json
  src/internal/live-common-setup.js
  src/live-common-set-supported-currencies.js
  src/live-common-setup.js
  src/renderer/modals/MigrateAccounts/index.js
  src/renderer/reducers/settings.js
  src/renderer/screens/exchange/hooks.js
  src/renderer/screens/manager/AppsList/Item.js
  src/renderer/screens/settings/sections/Accounts/BlacklistedTokens.js
  yarn.lock
Labels: important

#3191 LL-3337 fix deeplinking uri schemes
  package.json
  src/renderer/hooks/useDeeplinking.js
  yarn.lock
Labels: QA
