Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-11, with the labels that each got.

#3260 Release notes modal to filter out invalid tag names
  src/renderer/modals/ReleaseNotes/ReleaseNotesBody.js
Labels: QA

#3265 LL-3774 Add a warning banner for ongoing scam campaigns
  src/config/urls.js
  src/renderer/components/banners/OngoingScams.js
  src/renderer/screens/dashboard/index.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/firmware-update-8-back-to-dashboard-snap.png
Labels: QA

#3246 fix ctrl-r not working when app crashes
  src/renderer/App.js
  src/renderer/Default.js
  src/renderer/components/ThrowBlock.js
Labels: QA

#3277 live-common 15.7.x
  package.json
  src/renderer/screens/lend/Account/AccountBodyHeader.js
  src/renderer/screens/lend/modals/Supply/Body.js
  static/i18n/en/app.json
  yarn.lock
Labels: important

#3266 LL-3578 specify event category on some tezos flow
  src/renderer/families/tezos/DelegateFlowModal/Body.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepAccount.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepConfirmation.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepConnectDevice.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepCustom.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepStarter.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepSummary.js
  src/renderer/families/tezos/DelegateFlowModal/steps/StepValidator.js
  src/renderer/families/tezos/DelegateFlowModal/types.js
  src/renderer/families/tezos/Delegation/ContextMenu.js
  src/renderer/modals/Receive/Body.js
  src/renderer/modals/Receive/steps/StepAccount.js
  src/renderer/modals/Receive/steps/StepConnectDevice.js
  src/renderer/modals/Receive/steps/StepReceiveFunds.js
Labels: QA

#3271 Ll 3813 lending banners
  src/config/urls.js
  src/renderer/components/Carousel/banners/BlackFriday/images/circle.png
  src/renderer/components/Carousel/banners/BlackFriday/images/nanos.png
  src/renderer/components/Carousel/banners/BlackFriday/images/nanox.png
  src/renderer/components/Carousel/banners/BlackFriday/index.js
  src/renderer/components/Carousel/banners/Lending/images/1.png
  src/renderer/components/Carousel/banners/Lending/images/2.png
  src/renderer/components/Carousel/banners/Lending/images/3.png
  src/renderer/components/Carousel/banners/Lending/images/bg.png
  src/renderer/components/Carousel/banners/Lending/index.js
  src/renderer/components/Carousel/helpers.js
  src/renderer/components/Carousel/index.js
  static/i18n/en/app.json
Labels: HODL

#3272 LL-3445 Navigate to Swap history after completing a swap
  src/renderer/modals/Swap/SwapBody.js
  src/renderer/modals/Swap/index.js
  src/renderer/screens/swap/Form/index.js
  src/renderer/screens/swap/Swap.js
  src/renderer/screens/swap/index.js
Labels: QA

#3292 live-common 15.8.0
  package.json
  src/renderer/components/Carousel/banners/BlackFriday/index.js
  src/renderer/components/Carousel/banners/Lending/index.js
  yarn.lock
Labels: QA, important

#3288 events/compound
  src/renderer/screens/lend/Dashboard/index.js
  src/renderer/screens/lend/modals/Enable/Body.js
  src/renderer/screens/lend/modals/EnableInfoModal/index.js
  src/renderer/screens/lend/modals/ManageLend/index.js
  src/renderer/screens/lend/modals/Supply/Body.js
  src/renderer/screens/lend/modals/Withdraw/Body.js
Labels: QA

#3270 LL-3816 (Analytics) add source for tracking page events
  src/renderer/analytics/TrackPage.js
  src/renderer/components/AccountDistribution/Row.js
  src/renderer/components/AssetDistribution/Row.js
  src/renderer/components/Breadcrumb/AccountCrumb.js
  src/renderer/components/Breadcrumb/AssetCrumb.js
  src/renderer/components/BuyButton.js
  src/renderer/components/Carousel/banners/BuyCrypto/index.js
  src/renderer/components/Carousel/banners/StakeAlgorand/index.js
  src/renderer/components/Carousel/banners/StakeCosmos/index.js
  src/renderer/components/Carousel/banners/Swap/index.js
  src/renderer/components/ContextMenu/AccountContextMenu.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/NavigationGuard.js
  src/renderer/components/RepairDeviceButton.js
  src/renderer/components/Stars/Item.js
  src/renderer/components/TopBar/index.js
  src/renderer/hooks/useDeeplinking.js
  src/renderer/modals/OperationDetails/index.js
  src/renderer/modals/SwapOperationDetails/SwapOperationDetailsBody.js
  src/renderer/screens/account/AccountHeaderActions.js
  src/renderer/screens/account/EmptyStateAccount.js
  src/renderer/screens/account/TokensList.js
  src/renderer/screens/accounts/index.js
  src/renderer/screens/dashboard/index.js
  src/renderer/screens/settings/index.js
  src/renderer/screens/settings/sections/Help/RepairDeviceButton.js
  tests/specs/__image_snapshots__/firmware-update-0-manager-page-snap.png
  tests/specs/__image_snapshots__/firmware-update-1-disclaimer-modal-snap.png
  tests/specs/__image_snapshots__/firmware-update-2-disclaimer-modal-checkbox-snap.png
  tests/specs/__image_snapshots__/firmware-update-6-flash-mcu-done-snap.png
  tests/specs/__image_snapshots__/firmware-update-7-close-modal-snap.png
  tests/specs/__image_snapshots__/firmware-update-8-back-to-dashboard-snap.png
  tests/specs/__image_snapshots__/onboarding-3-screen-nano-x-snap.png
Labels: QA

#3287 fix/wordings
  src/renderer/screens/lend/modals/ManageLend/index.js
  static/i18n/en/app.json
Labels: QA

#3293 remove BCH warnings
  src/config/urls.js
  src/renderer/components/CurrencyDownStatusAlert.js
  static/i18n/en/app.json
Labels: QA

#3298 live-common 17.0.0
  package.json
  src/renderer/Default.js
  src/renderer/actions/accounts.js
  src/renderer/components/AccountDistribution/Row.js
  src/renderer/components/AccountDistribution/index.js
  src/renderer/experimental.js
  src/renderer/screens/account/AccountBalanceSummaryHeader.js
  src/renderer/screens/account/BalanceSummary.js
  src/renderer/screens/account/index.js
  src/renderer/screens/accounts/AccountList/index.js
  src/renderer/screens/accounts/AccountRowItem/Countervalue.js
  src/renderer/screens/accounts/AccountRowItem/Delta.js
  src/renderer/screens/asset/AssetHeader.js
  src/renderer/screens/asset/BalanceSummary.js
  yarn.lock
Labels: important

#3302 LL-3632 enable blackfriday banner
  src/renderer/components/Carousel/helpers.js
  src/renderer/components/Carousel/index.js
Labels: QA, important

#3295 LL-2868 - added utm tags in all URL
  src/config/urls.js
Labels: QA

#3304 LL-3521 Restore hide tokens setting section and add toggle
  src/renderer/screens/settings/sections/Accounts/BlacklistedTokens.js
  src/renderer/screens/settings/sections/Accounts/index.js
  static/i18n/en/app.json
Labels: QA

#3310 live-common 17.1.0
  package.json
  yarn.lock
Labels: QA, important

#3314 LL-3942 Replace illustration for compound empty state
  src/renderer/images/compound.svg
Labels: QA

#3316 fix(CheckBox): use defaultChecked to avoid react complaining
  src/renderer/components/CheckBox.js
Labels: QA

#3315 fix(Cosmos): show units in AccountBalanceSummaryFooter balances
  src/renderer/families/cosmos/AccountBalanceSummaryFooter.js
Labels: QA

#3300 Fixes errors to be visible again in Sync state
  src/renderer/bridge/BridgeSyncContext.js
  src/renderer/components/Tooltip.js
  src/renderer/styles/global.js
Labels: QA

#3325 LL-3980 reorder banners
  src/renderer/screens/dashboard/index.js
Labels: QA, important

#3317 Show time inside the tooltip on account charts when week range is selected
  src/renderer/screens/account/BalanceSummary.js
  src/renderer/screens/dashboard/GlobalSummary.js
Labels: QA

#3327 Fix regression in Price component
  src/renderer/components/Price.js
Labels: QA

#3320 LL-3939 (Lending): removal of ETH high fees warning
  src/renderer/modals/index.js
  src/renderer/screens/lend/Account/AccountBodyHeader.js
  src/renderer/screens/lend/Dashboard/index.js
  src/renderer/screens/lend/modals/HighFeesModal/index.js
Labels: QA

#3321 fix(EarnRewardsInfoModal): add margin between footer buttons
  src/renderer/components/EarnRewardsInfoModal.js
Labels: QA

#3326 LL-3854 – compound error handling fixes
  src/renderer/families/ethereum/GasPriceField.js
  src/renderer/hooks/useSpoilerForTransaction.js
  src/renderer/modals/Unfreeze/Body.js
  src/renderer/screens/lend/modals/Enable/Body.js
  src/renderer/screens/lend/modals/Enable/steps/StepAmount.js
  src/renderer/screens/lend/modals/Enable/steps/StepConfirmation.js
  src/renderer/screens/lend/modals/Enable/types.js
  src/renderer/screens/lend/modals/Supply/Body.js
  src/renderer/screens/lend/modals/Supply/steps/StepAmount.js
  src/renderer/screens/lend/modals/Supply/steps/StepConfirmation.js
  src/renderer/screens/lend/modals/Supply/types.js
  src/renderer/screens/lend/modals/Withdraw/Body.js
  src/renderer/screens/lend/modals/Withdraw/steps/StepAmount.js
  src/renderer/screens/lend/modals/Withdraw/steps/StepConfirmation.js
  src/renderer/screens/lend/modals/Withdraw/types.js
Labels: QA

#3291 LL-3081 Satstack feature
  src/config/urls.js
  src/internal/commands/checkRPCNodeConfig.js
  src/internal/commands/getSatStackStatus.js
  src/internal/commands/index.js
  src/internal/commands/scanDescriptors.js
  src/main/setup.js
  src/renderer/actions/accounts.js
  src/renderer/actions/settings.js
  src/renderer/components/Button.js
  src/renderer/components/CurrencyBadge.js
  src/renderer/components/InfoBox.js
  src/renderer/components/Label.js
  src/renderer/components/Link.js
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/OpenUserDataDirectoryBtn.js
  src/renderer/components/ProgressCircle.js
  src/renderer/components/RenderError.js
  src/renderer/components/Spinner.js
  src/renderer/hooks/useSatStackStatus.js
  src/renderer/icons/BlueSpinner/index.js
  src/renderer/icons/BlueSpinner/spinner.png
  src/renderer/icons/Server.js
  src/renderer/icons/SyncServer.js
  src/renderer/images/disconnect.png
  src/renderer/images/fullnode.png
  src/renderer/init.js
  src/renderer/modals/AddAccounts/FullNodeStatus.js
  src/renderer/modals/AddAccounts/steps/StepChooseCurrency.js
  src/renderer/modals/FullNode/FullNodeBody.js
  src/renderer/modals/FullNode/index.js
  src/renderer/modals/FullNode/steps/StepAccounts.js
  src/renderer/modals/FullNode/steps/StepConnectDevice.js
  src/renderer/modals/FullNode/steps/StepDisconnect.js
  src/renderer/modals/FullNode/steps/StepLanding.js
  src/renderer/modals/FullNode/steps/StepNode/Form.js
  src/renderer/modals/FullNode/steps/StepNode/index.js
  src/renderer/modals/FullNode/steps/StepSatStack.js
  src/renderer/modals/index.js
  src/renderer/reducers/accounts.js
  src/renderer/reducers/settings.js
  src/renderer/screens/accounts/AccountRowItem/index.js
  src/renderer/screens/accounts/AccountSyncStatusIndicator.js
  src/renderer/screens/settings/SettingsSection.js
  src/renderer/screens/settings/sections/Accounts/BlacklistedTokens.js
  src/renderer/screens/settings/sections/Accounts/Currencies.js
  src/renderer/screens/settings/sections/Accounts/FullNode.js
  src/renderer/screens/settings/sections/Accounts/FullNodeButton.js
  src/renderer/screens/settings/sections/Accounts/FullNodeStatus.js
  src/renderer/screens/settings/sections/Accounts/index.js
  src/renderer/screens/settings/sections/Experimental/index.js
  src/renderer/screens/settings/sections/Help/index.js
  src/renderer/storage.js
  src/renderer/styles/theme.js
  static/i18n/en/app.json
  yarn.lock
Labels: QA
