Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2020-12, with the labels that each got.

#3351 Open path to user data instead of parent folder
  src/renderer/components/OpenUserDataDirectoryBtn.js
Labels: important

#3347 live-common 17.3.x
  package.json
  src/renderer/components/OperationsList/SectionTitle.js
  src/renderer/screens/exchange/swap/History/index.js
  static/i18n/en/app.json
  yarn.lock
Labels: important

#3341 LL-2846 add warning box when utxo > 50
  src/renderer/components/InfoBox.js
  src/renderer/modals/Send/steps/StepSummary.js
  static/i18n/en/app.json
Labels: QA

#3349 Make unavailable swap error more generic
  static/i18n/en/app.json
Labels: QA

#3335 LL-3943 comment out phishing banner
  src/renderer/components/banners/OngoingScams.js
  src/renderer/screens/dashboard/index.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/__start__account-snap.png
  tests/specs/__image_snapshots__/__start__firmwareupdate-snap.png
  tests/specs/__image_snapshots__/__start__settings-snap.png
  tests/specs/__image_snapshots__/__start__swap-snap.png
  tests/specs/__image_snapshots__/firmware-update-8-back-to-dashboard-snap.png
Labels: QA

#3334 LL-3900 if no device currently use lastDeviceSeen in events context
  src/renderer/analytics/segment.js
Labels: QA

#3329 LL-3969 fix white screen bug
  src/renderer/components/ExportLogsButton.js
Labels: QA

#3337 LL-3731 change ctas order on last swap step
  src/renderer/modals/Swap/steps/StepFinished.js
  tests/specs/__image_snapshots__/swap-end-0-snap.png
Labels: QA

#3373 live-common 17.4.0
  package.json
  src/main/setup.js
  src/renderer/bridge/cache.js
  src/renderer/bridge/proxy.js
  src/renderer/modals/AddAccounts/steps/StepImport.js
  src/renderer/modals/FullNode/FullNodeBody.js
  src/renderer/modals/FullNode/index.js
  src/renderer/modals/FullNode/steps/StepAccounts.js
  src/renderer/modals/FullNode/steps/StepConnectDevice.js
  src/renderer/modals/FullNode/steps/StepSatStack.js
  src/renderer/screens/settings/sections/Accounts/FullNodeStatus.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/__start__swap-snap.png
  yarn.lock
Labels: QA, important

#3392 Hide onboarding lang picker
  src/config/languages.js
  src/renderer/components/Onboarding/Screens/Welcome/index.js
Labels: important

#3410 Remove unused files from LLD
  src/renderer/components/Carousel/banners/StakeCosmos/images/bg.png
  src/renderer/components/Carousel/banners/StakeCosmos/images/coin.png
  src/renderer/components/Carousel/banners/StakeCosmos/images/coin2.png
  src/renderer/components/Carousel/banners/StakeCosmos/images/coin3.png
  src/renderer/components/Carousel/banners/StakeCosmos/index.js
  src/renderer/components/Onboarding/Screens/Welcome/assets/Wave.js
  src/renderer/families/tezos/Delegation/DelegationBanner.js
  src/renderer/icons/Cart.js
  src/renderer/icons/Lending.js
  src/renderer/icons/Recover.js
  src/renderer/icons/Reddit.js
  src/renderer/icons/Server.js
  src/renderer/images/ledger-nano-s-onb.svg
  src/renderer/images/ledger-nano-x-error-onb.svg
  src/renderer/images/ledger-nano-x-onb.svg
  src/renderer/images/select-pin-blue-onb.svg
  src/renderer/images/select-pin-nano-onb.svg
  src/renderer/images/select-pin-nano-x-onb.svg
  src/renderer/images/write-seed-onb.svg
Labels: QA

#3390 add opened loans to lend
  package.json
  src/renderer/screens/lend/Opened/OpenedLoans.js
  src/renderer/screens/lend/Opened/index.js
  src/renderer/screens/lend/index.js
  static/i18n/en/app.json
  yarn.lock
Labels: QA

#3359 add swap infos in the validate on device screen
  src/renderer/components/DeviceAction/index.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/modals/Swap/SwapBody.js
  src/renderer/modals/Swap/index.js
  src/renderer/modals/Swap/steps/StepDevice.js
  src/renderer/screens/exchange/swap/Form/index.js
  static/i18n/en/app.json
Labels: QA
