Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2021-04, with the labels that each got.

#3707 LL-5073 fix firmware update
  package.json
  src/renderer/modals/UpdateFirmwareModal/index.js
  src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.js
  src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.js
  src/renderer/modals/UpdateFirmwareModal/steps/02-step-updating.js
  yarn.lock
Labels: QA, important

#3675 LL-4858 add erc20 accounts
  src/renderer/components/CurrencyBadge.js
  src/renderer/components/Receive2NoDevice.js
  src/renderer/modals/AddAccounts/steps/StepFinish.js
  tests/common.js
  tests/po/addAccountsModal.page.js
  tests/po/receiveModal.page.js
  tests/specs/__image_snapshots__/__start__sub-accounts-snap.png
  tests/specs/__image_snapshots__/addAccount-chainlink-no-parent-snap.png
  tests/specs/__image_snapshots__/addAccount-must-no-parent-snap.png
  tests/specs/__image_snapshots__/addAccount-receive-on-parent-1-snap.png
  tests/specs/__image_snapshots__/addAccount-receive-on-parent-2-snap.png
  tests/specs/__image_snapshots__/addAccount-receive-on-subaccount-1-snap.png
  tests/specs/__image_snapshots__/addAccount-receive-on-subaccount-2-snap.png
  tests/specs/__image_snapshots__/addAccount-selectParent-snap.png
  tests/specs/__image_snapshots__/addAccount-selectSubAccount-snap.png
  tests/specs/__image_snapshots__/addAccount-tokenWithoutParent-snap.png
  tests/specs/accounts/subaccount.spec.js
  tests/specs/settings/developermode.spec.js
Labels: QA

#3694 [LL-4756] feat : add select all in export operation history
  src/renderer/modals/ExportOperations/index.js
  tests/specs/__image_snapshots__/bitcoin-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/bitcoin-export-operations-history-modal-open-snap.png
  tests/specs/__image_snapshots__/cosmos-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/cosmos-export-operations-history-modal-open-snap.png
  tests/specs/__image_snapshots__/ethereum-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/ethereum-export-operations-history-modal-open-snap.png
  tests/specs/__image_snapshots__/global-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/global-export-operations-history-modal-open-snap.png
  tests/specs/__image_snapshots__/tezos-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/tezos-export-operations-history-modal-open-snap.png
  tests/specs/__image_snapshots__/xrp-export-operations-history-modal-accounts-selected-snap.png
  tests/specs/__image_snapshots__/xrp-export-operations-history-modal-open-snap.png
Labels: QA

#3723 LL-5049 Polkadot remove alert on retry for staking transactions
  src/renderer/families/polkadot/BondFlowModal/Body.js
  src/renderer/families/polkadot/RebondFlowModal/Body.js
  src/renderer/families/polkadot/UnbondFlowModal/Body.js
Labels: QA

#3718 LL-4825 - fix(Buy): update without my device button UI + wording
  src/renderer/modals/ExchangeDeviceConfirm/index.js
  static/i18n/en/app.json
Labels: QA

#3732 Bump live-common 19.4.0
  package.json
  tests/specs/__image_snapshots__/swap-rates-snap.png
  tests/specs/__image_snapshots__/swap-summary-step-snap.png
  yarn.lock
Labels: QA

#3757 LL-4613 Inline installation on connectApp flows as experimental
  package.json
  src/renderer/bridge/proxy-commands.js
  src/renderer/components/DeviceAction/index.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/experimental.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/global-experimental-features-snap.png
  tests/specs/__image_snapshots__/settings-experiemntal-snap.png
  yarn.lock
Labels: important

#3759 LL-5252 - fix scroll on status informations
  src/renderer/components/TopBar/NotificationIndicator/ServiceStatusPanel.js
Labels: QA
