Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2021-02, with the labels that each got.

#3513 LL-4391 Analytics and stylings for starred sidebar
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/Stars/Item.js
  src/renderer/components/Stars/Star.js
  src/renderer/screens/accounts/index.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/__start__account-snap.png
  tests/specs/__image_snapshots__/__start__appUpdater-snap.png
  tests/specs/__image_snapshots__/__start__firmwareupdate-snap.png
  tests/specs/__image_snapshots__/__start__global-snap.png
  tests/specs/__image_snapshots__/__start__manager-snap.png
  tests/specs/__image_snapshots__/__start__settings-snap.png
  tests/specs/__image_snapshots__/__start__swap-snap.png
  tests/specs/__image_snapshots__/account-display-grid-snap.png
  tests/specs/__image_snapshots__/account-display-list-snap.png
  tests/specs/__image_snapshots__/addAccount-selectParent-snap.png
  tests/specs/__image_snapshots__/addAccount-selectSubAccount-snap.png
  tests/specs/__image_snapshots__/addAccount-tokenWithoutParent-snap.png
  tests/specs/__image_snapshots__/app-updater-error-with-carousel-snap.png
  tests/specs/__image_snapshots__/app-updater-error-without-carousel-snap.png
  tests/specs/__image_snapshots__/app-updater-idle-snap.png
  tests/specs/__image_snapshots__/edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/firmware-update-0-manager-page-snap.png
  tests/specs/__image_snapshots__/firmware-update-1-disclaimer-modal-snap.png
  tests/specs/__image_snapshots__/firmware-update-2-disclaimer-modal-checkbox-snap.png
  tests/specs/__image_snapshots__/firmware-update-4-download-mcu-modal-snap.png
  tests/specs/__image_snapshots__/firmware-update-5-flash-mcu-start-snap.png
  tests/specs/__image_snapshots__/firmware-update-6-flash-mcu-done-snap.png
  tests/specs/__image_snapshots__/firmware-update-7-close-modal-snap.png
  tests/specs/__image_snapshots__/firmware-update-8-back-to-dashboard-snap.png
  tests/specs/__image_snapshots__/global-collapse-sidebar-snap.png
  tests/specs/__image_snapshots__/global-discreet-mode-snap.png
  tests/specs/__image_snapshots__/global-dismiss-carousel-snap.png
  tests/specs/__image_snapshots__/global-experimental-features-snap.png
  tests/specs/__image_snapshots__/global-receive-modal-snap.png
  tests/specs/__image_snapshots__/global-send-modal-snap.png
  tests/specs/__image_snapshots__/global-starred-account-snap.png
  tests/specs/__image_snapshots__/manager-appsOnDevice-snap.png
  tests/specs/__image_snapshots__/manager-catalog-snap.png
  tests/specs/__image_snapshots__/manager-install-tron-snap.png
  tests/specs/__image_snapshots__/manager-uninstall-tron-snap.png
  tests/specs/__image_snapshots__/manager-updateAll-snap.png
  tests/specs/__image_snapshots__/onboarding-complete-snap.png
  tests/specs/__image_snapshots__/remove-account-after-snap.png
  tests/specs/__image_snapshots__/remove-account-before-snap.png
  tests/specs/__image_snapshots__/sort-account-default-snap.png
  tests/specs/__image_snapshots__/sort-account-highest-balance-snap.png
  tests/specs/__image_snapshots__/sort-account-lowest-balance-snap.png
  tests/specs/__image_snapshots__/sort-account-name-asc-snap.png
  tests/specs/__image_snapshots__/sort-account-name-desc-snap.png
  tests/specs/__image_snapshots__/swap-access-snap.png
  tests/specs/__image_snapshots__/swap-end-0-snap.png
  tests/specs/__image_snapshots__/swap-end-1-snap.png
  tests/specs/__image_snapshots__/swap-history-modal-snap.png
  tests/specs/__image_snapshots__/swap-kyc-done-snap.png
  tests/specs/__image_snapshots__/swap-rates-snap.png
  tests/specs/__image_snapshots__/swap-summary-step-snap.png
Labels: QA

#3537 Wrongly formatted url for valentine day banner
  src/config/urls.js
Labels: QA, important

#3252 allow buy flow without device
  src/renderer/components/InfoBox.js
  src/renderer/components/Receive2NoDevice.js
  src/renderer/modals/ExchangeDeviceConfirm/index.js
  src/renderer/modals/Receive/steps/StepReceiveFunds.js
  static/i18n/en/app.json
Labels: QA

#3539 LL-4532 Remove backup pack banner
  src/renderer/components/Carousel/helpers.js
Labels: QA

#3516 LL-4448 Disable beginAtZero for the chart
  src/renderer/components/Chart/index.js
Labels: QA

#3354 [Coin Integration] Polkadot
  flow-typed/npm/moment_v2.x.x.js
  package.json
  src/config/urls.js
  src/renderer/components/OperationsList/AddressCell.js
  src/renderer/components/OperationsList/ConfirmationCheck.js
  src/renderer/components/SpendableAmount.js
  src/renderer/components/SpendableBanner.js
  src/renderer/families/polkadot/AccountBalanceSummaryFooter.js
  src/renderer/families/polkadot/AccountBodyHeader.js
  src/renderer/families/polkadot/AccountHeaderActions.js
  src/renderer/families/polkadot/BondFlowModal/Body.js
  src/renderer/families/polkadot/BondFlowModal/fields/AmountField.js
  src/renderer/families/polkadot/BondFlowModal/fields/RewardDestinationField.js
  src/renderer/families/polkadot/BondFlowModal/index.js
  src/renderer/families/polkadot/BondFlowModal/steps/StepAmount.js
  src/renderer/families/polkadot/BondFlowModal/steps/StepConfirmation.js
  src/renderer/families/polkadot/BondFlowModal/types.js
  src/renderer/families/polkadot/EarnRewardsInfoModal.js
  src/renderer/families/polkadot/ElectionStatusWarning.js
  src/renderer/families/polkadot/ManageModal.js
  src/renderer/families/polkadot/Nomination/Header.js
  src/renderer/families/polkadot/Nomination/Row.js
  src/renderer/families/polkadot/Nomination/UnsupportedWarning.js
  src/renderer/families/polkadot/Nomination/index.js
  src/renderer/families/polkadot/NominationFlowModal/Body.js
  src/renderer/families/polkadot/NominationFlowModal/fields/ValidatorRow.js
  src/renderer/families/polkadot/NominationFlowModal/fields/ValidatorsField.js
  src/renderer/families/polkadot/NominationFlowModal/index.js
  src/renderer/families/polkadot/NominationFlowModal/steps/StepConfirmation.js
  src/renderer/families/polkadot/NominationFlowModal/steps/StepNomination.js
  src/renderer/families/polkadot/NominationFlowModal/types.js
  src/renderer/families/polkadot/RebondFlowModal/Body.js
  src/renderer/families/polkadot/RebondFlowModal/fields/AmountField.js
  src/renderer/families/polkadot/RebondFlowModal/index.js
  src/renderer/families/polkadot/RebondFlowModal/steps/StepAmount.js
  src/renderer/families/polkadot/RebondFlowModal/steps/StepConfirmation.js
  src/renderer/families/polkadot/RebondFlowModal/types.js
  src/renderer/families/polkadot/SimpleOperationFlowModal/Body.js
  src/renderer/families/polkadot/SimpleOperationFlowModal/index.js
  src/renderer/families/polkadot/SimpleOperationFlowModal/steps/StepConfirmation.js
  src/renderer/families/polkadot/SimpleOperationFlowModal/steps/StepInfo.js
  src/renderer/families/polkadot/SimpleOperationFlowModal/types.js
  src/renderer/families/polkadot/TransactionConfirmFields.js
  src/renderer/families/polkadot/UnbondFlowModal/Body.js
  src/renderer/families/polkadot/UnbondFlowModal/fields/AmountField.js
  src/renderer/families/polkadot/UnbondFlowModal/index.js
  src/renderer/families/polkadot/UnbondFlowModal/steps/StepAmount.js
  src/renderer/families/polkadot/UnbondFlowModal/steps/StepConfirmation.js
  src/renderer/families/polkadot/UnbondFlowModal/types.js
  src/renderer/families/polkadot/components/CollapsibleList.js
  src/renderer/families/polkadot/operationDetails.js
  src/renderer/icons/Coins.js
  src/renderer/icons/VoteNay.js
  src/renderer/init.js
  src/renderer/modals/OperationDetails/index.js
  src/renderer/modals/index.js
  static/i18n/en/app.json
  static/i18n/fr/app.json
  yarn.lock
Labels: QA, important

#3571 fix swap fees unit
  src/renderer/components/DeviceAction/rendering.js
Labels: important

#3561 electron 11.2 + Cosmos (libcore + live-common)
  package.json
  src/config/urls.js
  src/live-common-set-supported-currencies.js
  src/renderer/components/CurrencyDownStatusAlert.js
  src/renderer/experimental.js
  src/renderer/modals/RepairModal/index.js
  src/renderer/screens/accounts/AccountRowItem/index.js
  src/renderer/screens/exchange/swap/Form/index.js
  static/i18n/en/app.json
  tests/flows/accounts/bookmarkAccount.js
  tests/flows/accounts/editAccountName.js
  tests/flows/accounts/hideToken.js
  tests/flows/accounts/removeAccount.js
  tests/po/accounts.page.js
  tests/specs/__image_snapshots__/cosmos-add-account-fill-input-snap.png
  tests/specs/__image_snapshots__/global-experimental-features-snap.png
  yarn.lock
Labels: QA, important

#3564 LL-4249 (Charts): fix width issue
  src/renderer/components/Chart/index.js
Labels: QA

#3558 LL-4459 - add need help tracking
  src/renderer/components/Onboarding/Screens/Tutorial/machines/setupNewDevice.js
Labels: QA

#3511 LLD will now try to fetch TERMS-{$language}.md and fallback to TERMS.md on 404 error
  src/renderer/terms.js
Labels: QA, important

#3573 LL-4603 [Windows] Fix `ledgerlive://` URI handling
  build/installer.nsh
  src/main/index.js
  src/renderer/hooks/useDeeplinking.js
Labels: QA

#3589 Mashup/2.23
  package.json
  src/config/urls.js
  src/internal/commands/firmwareUpdating.js
  src/internal/commands/index.js
  src/renderer/animations/nanoS/2FirmwareUpdating/dark.json
  src/renderer/animations/nanoS/2FirmwareUpdating/light.json
  src/renderer/components/DeviceAction/animations.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/components/InfoBox.js
  src/renderer/components/Input.js
  src/renderer/components/OperationsList/ConfirmationCell.js
  src/renderer/components/RequestAmount.js
  src/renderer/components/TransactionConfirm/index.js
  src/renderer/families/polkadot/BondFlowModal/fields/RewardDestinationField.js
  src/renderer/families/polkadot/TransactionConfirmFields.js
  src/renderer/families/polkadot/operationDetails.js
  src/renderer/modals/OperationDetails/index.js
  src/renderer/modals/UpdateFirmwareModal/index.js
  src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.js
  src/renderer/modals/UpdateFirmwareModal/steps/02-step-updating.js
  src/renderer/modals/UpdateFirmwareModal/steps/03-step-confirmation.js
  static/i18n/en/app.json
  static/i18n/fr/app.json
  tests/po/portfolio.page.js
  tests/specs/__image_snapshots__/firmware-update-6-flash-mcu-done-snap.png
  tests/specs/__image_snapshots__/global-help-drawer-snap.png
  tests/specs/global.spec.js
  yarn.lock
Labels: QA, important
