Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2021-03, with the labels that each got.

#3590 Prevent console error when parsin the svg path
  src/renderer/components/Onboarding/Screens/Tutorial/assets/AnimatedWave.js
Labels: QA

#3544 CI - use vercel to cancel previous flows
  .github/actions/post-comment/action.yml
  .github/actions/post-comment/index.js
  .github/actions/prepare-comment-body/action.yml
  .github/actions/prepare-comment-body/index.js
  .github/workflows/bundle-app.yml
  .github/workflows/checks.yml
Labels: HODL

#3637 disable analytics on mock or spectron runs
  src/renderer/analytics/inject-in-window.js
  src/renderer/analytics/segment.js
Labels: bug, important

#3603 [LL-4660] DOT label for bond, unbond, rebond is on right
  src/renderer/families/polkadot/BondFlowModal/fields/AmountField.js
  src/renderer/families/polkadot/RebondFlowModal/fields/AmountField.js
  src/renderer/families/polkadot/UnbondFlowModal/fields/AmountField.js
Labels: QA

#3623 LL-4374 Reduce height of settings tab
  src/renderer/components/TabBar.js
  src/renderer/screens/settings/index.js
  tests/specs/__image_snapshots__/global-experimental-features-snap.png
Labels: QA

#3487 LL-4344 Drop unused literals
  scripts/i18next-unused.py
  src/renderer/components/TransactionConfirm/index.js
  src/renderer/families/cosmos/ClaimRewardsFlowModal/steps/StepClaimRewards.js
  src/renderer/families/cosmos/ClaimRewardsFlowModal/steps/StepConfirmation.js
  src/renderer/modals/Freeze/steps/StepConfirmation.js
  src/renderer/modals/Help/index.js
  src/renderer/screens/lend/Account/Header.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/global-help-drawer-snap.png
Labels: QA

#3621 LL-4208 - fix assets distribution overflows
  src/renderer/components/AssetDistribution/Row.js
Labels: QA

#3624 LL-4608 Modal buttons overflow
  src/renderer/components/Button.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/components/ErrorDisplay.js
  src/renderer/components/ExportLogsButton.js
  src/renderer/modals/AddAccounts/steps/StepImport.js
Labels: QA

#3616 LL-4582 (EthInput): error and warning messages ellipsis issue
  src/renderer/components/FeeSliderField.js
  src/renderer/components/Input.js
  src/renderer/families/ethereum/GasLimitField.js
Labels: QA

#3630 feat(ReadOnlyAddressField): ensure address last line has MINLENGTH (5 chars) - LL-4656
  src/renderer/components/ReadOnlyAddressField.js
Labels: QA

#3625 live-common 18.6.0 + 18.7.0 + libcore
  cryptoassets.md
  package.json
  tests/specs/__image_snapshots__/global-experimental-features-snap.png
  tests/specs/__image_snapshots__/settings-experiemntal-snap.png
  yarn.lock
Labels: QA, important

#3591 LL-4431 (Onboarding): lang switcher activated
  src/config/languages.js
  src/renderer/components/Onboarding/LangSwitcher.js
  src/renderer/components/Onboarding/Pedagogy/screens.js
  src/renderer/components/Onboarding/Screens/Tutorial/Stepper.js
  src/renderer/components/Onboarding/Screens/Welcome/index.js
  src/renderer/terms.js
  tests/specs/__image_snapshots__/__start__onboarding-snap.png
Labels: QA

#3626 metamask - close current modals when using the bridge deeplink
  src/renderer/hooks/useDeeplinking.js
Labels: QA

#3592 LL-4481 - add mode to accounts page tracking
  src/renderer/screens/accounts/index.js
Labels: QA

#3611 LL-4576 (AccountScreen): header name overflowing issue
  src/renderer/screens/account/AccountHeader.js
Labels: QA

#3627 LL-4375 Countervalue: Remove one decimal from the Current Currency rate
  src/renderer/components/AssetDistribution/Row.js
  src/renderer/components/Price.js
  src/renderer/screens/exchange/swap/Form/To.js
  tests/specs/__image_snapshots__/bitcoin-account-operation-details-snap.png
  tests/specs/__image_snapshots__/bitcoin-account-operation-list-snap.png
  tests/specs/__image_snapshots__/bitcoin-bookmark-account-snap.png
  tests/specs/__image_snapshots__/bitcoin-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/bitcoin-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/cosmos-account-operation-details-snap.png
  tests/specs/__image_snapshots__/cosmos-account-operation-list-snap.png
  tests/specs/__image_snapshots__/cosmos-bookmark-account-snap.png
  tests/specs/__image_snapshots__/cosmos-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/cosmos-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/ethereum-bookmark-account-snap.png
  tests/specs/__image_snapshots__/ethereum-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/ethereum-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/ethereum-hide-token-after-snap.png
  tests/specs/__image_snapshots__/ethereum-hide-token-before-snap.png
  tests/specs/__image_snapshots__/global-bookmark-account-snap.png
  tests/specs/__image_snapshots__/global-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/global-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/global-hide-token-after-snap.png
  tests/specs/__image_snapshots__/global-hide-token-before-snap.png
  tests/specs/__image_snapshots__/global-starred-account-snap.png
  tests/specs/__image_snapshots__/tezos-account-operation-details-snap.png
  tests/specs/__image_snapshots__/tezos-account-operation-list-snap.png
  tests/specs/__image_snapshots__/tezos-bookmark-account-snap.png
  tests/specs/__image_snapshots__/tezos-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/tezos-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/xrp-account-operation-details-snap.png
  tests/specs/__image_snapshots__/xrp-account-operation-list-snap.png
  tests/specs/__image_snapshots__/xrp-bookmark-account-snap.png
  tests/specs/__image_snapshots__/xrp-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/xrp-edit-account-name-before-snap.png
Labels: QA

#3622 fix(Polkadot): Nominations - useDiscreetMode and round value to avoid leak
  src/renderer/families/polkadot/Nomination/Header.js
  src/renderer/families/polkadot/Nomination/Row.js
Labels: QA

#3620 fix(OperationList): avoid AccountCell to be shrinked if no address - …
  src/renderer/components/OperationsList/AddressCell.js
Labels: QA

#3619 LL-4655 Polkadot wording: change 'withdraw unbonded' to 'withdraw'
  static/i18n/en/app.json
Labels: QA

#3597 [LL-4638] put showmore outside of operation list
  src/renderer/components/OperationsList/index.js
Labels: QA

#3655 Ci/fix screenshots
  tests/specs/__image_snapshots__/__start__appUpdater-snap.png
  tests/specs/__image_snapshots__/__start__global-accounts-snap.png
  tests/specs/__image_snapshots__/__start__global-snap.png
  tests/specs/__image_snapshots__/__start__settings-password-lock-snap.png
  tests/specs/__image_snapshots__/__start__swap-snap.png
  tests/specs/__image_snapshots__/app-updater-error-with-carousel-snap.png
  tests/specs/__image_snapshots__/app-updater-error-without-carousel-snap.png
  tests/specs/__image_snapshots__/app-updater-idle-snap.png
  tests/specs/__image_snapshots__/bitcoin-account-operation-details-snap.png
  tests/specs/__image_snapshots__/bitcoin-account-operation-list-snap.png
  tests/specs/__image_snapshots__/bitcoin-bookmark-account-snap.png
  tests/specs/__image_snapshots__/bitcoin-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/bitcoin-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/cosmos-account-operation-details-snap.png
  tests/specs/__image_snapshots__/cosmos-account-operation-list-snap.png
  tests/specs/__image_snapshots__/cosmos-bookmark-account-snap.png
  tests/specs/__image_snapshots__/cosmos-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/cosmos-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/ethereum-bookmark-account-snap.png
  tests/specs/__image_snapshots__/ethereum-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/ethereum-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/ethereum-hide-token-after-snap.png
  tests/specs/__image_snapshots__/ethereum-hide-token-before-snap.png
  tests/specs/__image_snapshots__/global-bookmark-account-snap.png
  tests/specs/__image_snapshots__/global-collapse-sidebar-snap.png
  tests/specs/__image_snapshots__/global-discreet-mode-snap.png
  tests/specs/__image_snapshots__/global-dismiss-carousel-snap.png
  tests/specs/__image_snapshots__/global-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/global-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/global-help-drawer-snap.png
  tests/specs/__image_snapshots__/global-hide-token-after-snap.png
  tests/specs/__image_snapshots__/global-hide-token-before-snap.png
  tests/specs/__image_snapshots__/global-receive-modal-snap.png
  tests/specs/__image_snapshots__/global-send-modal-snap.png
  tests/specs/__image_snapshots__/global-starred-account-snap.png
  tests/specs/__image_snapshots__/tezos-account-operation-details-snap.png
  tests/specs/__image_snapshots__/tezos-account-operation-list-snap.png
  tests/specs/__image_snapshots__/tezos-bookmark-account-snap.png
  tests/specs/__image_snapshots__/tezos-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/tezos-edit-account-name-before-snap.png
  tests/specs/__image_snapshots__/xrp-account-operation-details-snap.png
  tests/specs/__image_snapshots__/xrp-account-operation-list-snap.png
  tests/specs/__image_snapshots__/xrp-bookmark-account-snap.png
  tests/specs/__image_snapshots__/xrp-edit-account-name-after-snap.png
  tests/specs/__image_snapshots__/xrp-edit-account-name-before-snap.png
Labels: QA

#3656 Revert "LL-4448 Disable beginAtZero for the chart"
  src/renderer/components/Chart/index.js
Labels: regression

#3647 LL-4584 - Add buy coins
  src/renderer/screens/exchange/config.js
Labels: QA

#3648 LL-4709 - no more oops
  static/i18n/en/app.json
Labels: QA

#3681 [LL-4404] (PrivacyPolicy): use specific url for each available language
  TERM.es.md
  TERM.ru.md
  src/config/urls.js
  src/renderer/modals/Terms/index.js
  src/renderer/screens/settings/sections/About/index.js
  src/renderer/terms.js
Labels: QA, important

#3562 LL-4446 Add support for floating rates on swap
  package.json
  src/renderer/animations/index.js
  src/renderer/animations/swap.json
  src/renderer/components/AnimatedCountdown.js
  src/renderer/components/ArrowSeparator.js
  src/renderer/components/ContextMenu/AccountContextMenu.js
  src/renderer/components/CountdownTimer.js
  src/renderer/components/DeviceAction/index.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/components/LinkWithExternalIcon.js
  src/renderer/components/MainSideBar/index.js
  src/renderer/components/SelectCurrency.js
  src/renderer/icons/Changelly.js
  src/renderer/icons/Countdown.js
  src/renderer/icons/LightBulb.js
  src/renderer/icons/Lock.js
  src/renderer/icons/LockOpen.js
  src/renderer/modals/Swap/steps/StepSummary.js
  src/renderer/modals/SwapOperationDetails/SwapOperationDetailsBody.js
  src/renderer/reducers/settings.js
  src/renderer/screens/account/AccountHeaderActions.js
  src/renderer/screens/exchange/Sell/SelectAccountAndCurrency.js
  src/renderer/screens/exchange/swap/Form/AnimatedArrows.js
  src/renderer/screens/exchange/swap/Form/CurrencyOptionRow.js
  src/renderer/screens/exchange/swap/Form/Footer.js
  src/renderer/screens/exchange/swap/Form/FromAccount.js
  src/renderer/screens/exchange/swap/Form/FromAmount.js
  src/renderer/screens/exchange/swap/Form/ToAccount.js
  src/renderer/screens/exchange/swap/Form/ToAmount.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/Pill.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/Provider.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/TooltipContent.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/index.js
  src/renderer/screens/exchange/swap/Form/index.js
  src/renderer/screens/exchange/swap/Swap.js
  static/i18n/en/app.json
  yarn.lock
Labels: QA, important

#3708 (Wording): fix missing onboarding quizz key
  static/i18n/de/app.json
  static/i18n/el/app.json
  static/i18n/en/app.json
  static/i18n/es/app.json
  static/i18n/fi/app.json
  static/i18n/fr/app.json
  static/i18n/hu/app.json
  static/i18n/it/app.json
  static/i18n/ja/app.json
  static/i18n/ko/app.json
  static/i18n/nl/app.json
  static/i18n/no/app.json
  static/i18n/pl/app.json
  static/i18n/pt/app.json
  static/i18n/ru/app.json
  static/i18n/sr/app.json
  static/i18n/sv/app.json
  static/i18n/tr/app.json
  static/i18n/zh/app.json
Labels: bug, important

#3700 LL-4446 Swap floating rates
  package.json
  src/renderer/components/DeviceAction/index.js
  src/renderer/components/DeviceAction/rendering.js
  src/renderer/screens/exchange/swap/Form/CurrencyOptionRow.js
  src/renderer/screens/exchange/swap/Form/Footer.js
  src/renderer/screens/exchange/swap/Form/FromAccount.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/Provider.js
  src/renderer/screens/exchange/swap/Form/index.js
  static/i18n/en/app.json
  tests/specs/__image_snapshots__/swap-kyc-done-snap.png
  yarn.lock
Labels: important
