Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2021-12, with the labels that each got.

#4488 Activate Polygon
  cryptoassets.md
  src/live-common-set-supported-currencies.js
Labels: important

#4493 New Crowdin updates
  static/i18n/fr/app.json
  static/i18n/ja/app.json
  static/i18n/tr/app.json
Labels: important

#4495 Ll 8456 add send buttons nfts + live-common bump
  package.json
  playwright/specs/settings.spec.ts-snapshots/settings-experimental-page-linux.png
  playwright/specs/settings.spec.ts-snapshots/settings-general-page-win32.png
  src/renderer/components/Breadcrumb/NFTCrumb.js
  src/renderer/drawers/NFTViewerDrawer/NFTProperties.js
  src/renderer/drawers/NFTViewerDrawer/index.js
  src/renderer/modals/Send/Body.js
  src/renderer/modals/Send/steps/StepRecipient.js
  src/renderer/screens/account/AccountHeaderActions.js
  src/renderer/screens/nft/Gallery/Gallery.js
  src/renderer/screens/nft/Gallery/TokensList/Item.js
  src/renderer/screens/nft/Gallery/TokensList/TokensList.js
  src/renderer/screens/nft/Send/SelectNFT.js
  yarn.lock
Labels: important

#4504 update live-common & also LL-8264 Fixes the confirmation check to go green on NFT IN
  package.json
  playwright/specs/settings.spec.ts-snapshots/settings-experimental-page-win32.png
  src/renderer/components/OperationsList/AmountCell.js
  src/renderer/components/OperationsList/ConfirmationCheck.js
  yarn.lock
Labels: important

#4375 refacto: remove unused swap1 files
  src/renderer/animations/swap.json
  src/renderer/icons/WorldMap.js
  src/renderer/images/swap.png
  src/renderer/screens/exchange/swap/Form/AnimatedArrows.js
  src/renderer/screens/exchange/swap/Form/FromAccount.js
  src/renderer/screens/exchange/swap/Form/FromAmount.js
  src/renderer/screens/exchange/swap/Form/ToAccount.js
  src/renderer/screens/exchange/swap/Form/ToAmount.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/Pill.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/Provider.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/TooltipContent.js
  src/renderer/screens/exchange/swap/Form/TradeMethod/index.js
  src/renderer/screens/exchange/swap/Form/index.js
  src/renderer/screens/exchange/swap/History/index.js
  src/renderer/screens/exchange/swap/KYC/Pending.js
  src/renderer/screens/exchange/swap/KYC/index.js
  src/renderer/screens/exchange/swap/Loading.js
  src/renderer/screens/exchange/swap/NotAvailable.js
  src/renderer/screens/exchange/swap/index.js
Labels: merge conflicts

#4018 LL-7199 Deliver the crypto_org UI components
  src/config/urls.js
  src/renderer/families/crypto_org/AccountSubHeader.js
  src/renderer/families/crypto_org/AccountSubHeaderDrawer.js
  src/renderer/families/crypto_org/MemoValueField.js
  src/renderer/families/crypto_org/SendRecipientFields.js
  src/renderer/modals/Receive/steps/StepAccount.js
  static/i18n/en/app.json
Labels: QA

#4501 LL-8553 - add subAccount playwright
  playwright/models/AccountsPage.ts
  playwright/models/AddAccountModal.ts
  playwright/models/Layout.ts
  playwright/models/ManagerPage.ts
  playwright/models/ReceiveModal.ts
  playwright/specs/account.spec.ts
  playwright/specs/manager.spec.ts-snapshots/manager-install-tron-linux.png
  playwright/specs/manager.spec.ts-snapshots/manager-install-tron-win32.png
  playwright/specs/manager.spec.ts-snapshots/manager-installed-apps-linux.png
  playwright/specs/manager.spec.ts-snapshots/manager-installed-apps-win32.png
  playwright/specs/manager.spec.ts-snapshots/manager-uninstall-tron-linux.png
  playwright/specs/manager.spec.ts-snapshots/manager-uninstall-tron-win32.png
  playwright/specs/manager.spec.ts-snapshots/manager-updateAll-linux.png
  playwright/specs/manager.spec.ts-snapshots/manager-updateAll-win32.png
  playwright/specs/subAccounts.spec.ts
  playwright/specs/subAccounts.spec.ts-snapshots/parent-addAccount-result-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/parent-addAccount-result-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/parent-address-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/parent-address-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/parent-exists-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/parent-exists-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/select-account-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/select-account-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/select-parent-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/select-parent-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-address-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-address-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-exist-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-exist-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-noParent-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-noParent-win32.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-parent-exists-linux.png
  playwright/specs/subAccounts.spec.ts-snapshots/subAccount-parent-exists-win32.png
  src/renderer/components/Receive2NoDevice.js
  src/renderer/modals/AddAccounts/steps/StepChooseCurrency.js
  src/renderer/modals/Receive/steps/StepAccount.js
  src/renderer/modals/Receive/steps/StepConnectDevice.js
  src/renderer/modals/Receive/steps/StepReceiveFunds.js
  src/renderer/screens/accounts/AccountsHeader.js
  src/renderer/screens/manager/AppsList/AppActions.js
  src/renderer/screens/manager/AppsList/Progress.js
  src/renderer/screens/manager/AppsList/UpdateAllApps.js
Labels: merge conflicts
