Repository LedgerHQ/ledger-live-desktop, pull requests merged in 2022-04, with the labels that each got.

#4867 Sunset Libcore
  package.json
  src/index.js
  src/internal/commands/index.js
  src/internal/commands/libcoreGetVersion.js
  src/internal/commands/libcoreReset.js
  src/internal/implement-libcore.js
  src/internal/live-common-setup.js
  src/main/internal-lifecycle.js
  src/renderer/Default.js
  src/renderer/bridge/BridgeSyncContext.js
  src/renderer/components/LibcoreBusyIndicator.js
  src/renderer/events.js
  src/renderer/experimental.js
  src/renderer/init.js
  src/renderer/reset.js
  static/i18n/en/app.json
  yarn.lock
Labels: feature ready

#4870 [LIVE-1174] - Feature: Upgrade NFT architecture
  package.json
  src/helpers/nftLinksFactory.js
  src/renderer/bridge/proxy.js
  src/renderer/components/Breadcrumb/NFTCrumb.js
  src/renderer/components/ContextMenu/NFTContextMenu.js
  src/renderer/components/DropDownSelector.js
  src/renderer/drawers/NFTViewerDrawer/ExternalViewerButton.js
  src/renderer/drawers/NFTViewerDrawer/index.js
  src/renderer/drawers/OperationDetails/NFTOperationDetails.js
  src/renderer/drawers/OperationDetails/index.js
  src/renderer/families/ethereum/operationDetails.js
  src/renderer/modals/Send/Body.js
  src/renderer/modals/Send/steps/StepAmount.js
  src/renderer/screens/nft/CollectionName.js
  src/renderer/screens/nft/Collections/Collections.js
  src/renderer/screens/nft/Collections/Row.js
  src/renderer/screens/nft/Gallery/Collection.js
  src/renderer/screens/nft/Gallery/Gallery.js
  src/renderer/screens/nft/Gallery/TokensList/Item.js
  src/renderer/screens/nft/Gallery/TokensList/TokensList.js
  src/renderer/screens/nft/Send/Option.js
  src/renderer/screens/nft/Send/SelectNFT.js
  src/renderer/screens/nft/Send/Summary.js
  static/i18n/en/app.json
  yarn.lock
Labels: dependencies, feature ready

#4884 LIVE-1751 Solana staking
  src/config/urls.js
  src/renderer/components/Delegation/ValidatorRow.js
  src/renderer/families/solana/AccountBalanceSummaryFooter.js
  src/renderer/families/solana/AccountBodyHeader.js
  src/renderer/families/solana/AccountHeaderManageActions.js
  src/renderer/families/solana/Delegation/Header.js
  src/renderer/families/solana/Delegation/Row.js
  src/renderer/families/solana/Delegation/index.js
  src/renderer/families/solana/DelegationActivateFlowModal/Body.js
  src/renderer/families/solana/DelegationActivateFlowModal/index.js
  src/renderer/families/solana/DelegationActivateFlowModal/steps/StepConfirmation.js
  src/renderer/families/solana/DelegationActivateFlowModal/steps/StepValidator.js
  src/renderer/families/solana/DelegationActivateFlowModal/types.js
  src/renderer/families/solana/DelegationDeactivateFlowModal/Body.js
  src/renderer/families/solana/DelegationDeactivateFlowModal/index.js
  src/renderer/families/solana/DelegationDeactivateFlowModal/steps/StepConfirmation.js
  src/renderer/families/solana/DelegationDeactivateFlowModal/steps/StepValidator.js
  src/renderer/families/solana/DelegationDeactivateFlowModal/types.js
  src/renderer/families/solana/DelegationFlowModal/Body.js
  src/renderer/families/solana/DelegationFlowModal/Info/index.js
  src/renderer/families/solana/DelegationFlowModal/index.js
  src/renderer/families/solana/DelegationFlowModal/steps/StepAmount.js
  src/renderer/families/solana/DelegationFlowModal/steps/StepConfirmation.js
  src/renderer/families/solana/DelegationFlowModal/steps/StepValidator.js
  src/renderer/families/solana/DelegationFlowModal/types.js
  src/renderer/families/solana/DelegationReactivateFlowModal/Body.js
  src/renderer/families/solana/DelegationReactivateFlowModal/index.js
  src/renderer/families/solana/DelegationReactivateFlowModal/steps/StepConfirmation.js
  src/renderer/families/solana/DelegationReactivateFlowModal/steps/StepValidator.js
  src/renderer/families/solana/DelegationReactivateFlowModal/types.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/Body.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/fields/AmountField.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/index.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/steps/StepAmount.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/steps/StepConfirmation.js
  src/renderer/families/solana/DelegationWithdrawFlowModal/types.js
  src/renderer/families/solana/shared/components/Ellipsis.js
  src/renderer/families/solana/shared/components/ErrorDisplay.js
  src/renderer/families/solana/shared/components/LedgerByFigmentTCLink.js
  src/renderer/families/solana/shared/components/ValidatorRow.js
  src/renderer/families/solana/shared/fields/ValidatorsField.js
  src/renderer/modals/index.js
  static/i18n/en/app.json
Labels: dependencies, feature ready

#4832 LIVE-1653 - Fix experimental countervalues toggle
  src/renderer/experimental.js
  src/renderer/screens/settings/sections/Experimental/ExperimentalSwitch.js
Labels: QA
